iamge:
  name: traefik
  tag: 2.1.3

dashboard:
  enable: true

additionalArguments:
- --certificatesresolvers.ssl.acme.tlschallenge=true
- --certificatesresolvers.ssl.acme.email=alex@arlyon.dev
- --certificatesresolvers.ssl.acme.storage=acme.json