apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app: guacamole
spec:
  storageClassName: nfs-client
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/guac-mysql/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: guacamole-mysql
  namespace: guacamole
  labels:
    app: guacamole-mysql
spec:
  storageClassName: nfs-client
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/guac-mysql/data"
